# Generated by Django 4.0.3 on 2022-05-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='shopname',
            field=models.CharField(choices=[('uttara', 'uttara'), ('badda', 'badda')], max_length=200, null=True),
        ),
    ]
