# Generated by Django 4.0.3 on 2022-06-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_price_useritem_customer_useritem_left_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='left',
        ),
    ]
