# Generated by Django 4.0.3 on 2022-06-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_price_order_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='UserItem',
        ),
        migrations.AddField(
            model_name='order',
            name='UserItem',
            field=models.ManyToManyField(blank=True, to='core.useritem'),
        ),
    ]
