# Generated by Django 4.0.3 on 2022-06-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shopname',
        ),
    ]
