# Generated by Django 4.0.3 on 2022-06-26 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sellprice',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
