# Generated by Django 4.0.3 on 2022-07-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_product_groupname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold',
            name='customerupdate',
        ),
        migrations.RemoveField(
            model_name='sold',
            name='quantityupdate',
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='customerupdate',
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='quantityupdate',
        ),
        migrations.AddField(
            model_name='sold',
            name='solddt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
