# Generated by Django 4.0.3 on 2022-07-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_sold_solddt_sold_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='sold',
            name='last_updated',
        ),
    ]
