# Generated by Django 4.0.3 on 2022-07-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_order_phone_order_address_order_name_sold_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('exchange', 'exchange'), ('public', 'public')], default='public', max_length=10, null=True),
        ),
    ]
