# Generated by Django 4.0.3 on 2022-07-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_order_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritem',
            name='left',
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='paid',
        ),
        migrations.AddField(
            model_name='useritem',
            name='brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='useritem',
            name='engine_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='useritem',
            name='model_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
