# Generated by Django 4.0.3 on 2022-07-23 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_useritem_left_remove_useritem_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='enginecomplete',
            field=models.CharField(choices=[('complete', 'complete'), ('incomplete', 'incomplete')], default='incomplete', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='useritem',
            name='exchange_ammount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='useritem',
            name='exchange_engine',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='useritem',
            name='price1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='useritem',
            name='price2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='useritem',
            name='remarks',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='useritem',
            name='status',
            field=models.CharField(choices=[('Direct', 'Direct'), ('Exchange', 'Exchange')], default='Direct', max_length=10, null=True),
        ),
    ]
