# Generated by Django 4.0.3 on 2022-07-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_useritem_enginecomplete_useritem_exchange_ammount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritem',
            name='brand',
        ),
        migrations.AddField(
            model_name='useritem',
            name='productype',
            field=models.CharField(choices=[('Local', 'Local'), ('Container', 'Container')], default='Local', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='engine_no',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='enginecomplete',
            field=models.CharField(choices=[('complete', 'complete'), ('incomplete', 'incomplete')], default='complete', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='exchange_engine',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='model_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
