# Generated by Django 4.0.3 on 2022-07-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_useritem_brand_useritem_productype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='engine_no',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
