# Generated by Django 4.0.3 on 2022-07-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_order_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
