# Generated by Django 4.0.3 on 2022-07-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_order_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_id',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
