# Generated by Django 4.0.3 on 2022-07-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_order_invoice_id_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
