# Generated by Django 4.0.3 on 2022-07-25 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_sold_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
    ]
