# Generated by Django 4.0.3 on 2022-08-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_order_address_alter_order_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='credit',
            field=models.CharField(choices=[('credit', 'credit'), ('noncredit', 'noncredit')], default='credit', max_length=10, null=True),
        ),
    ]
