# Generated by Django 4.0.3 on 2022-08-14 06:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_supplier_mrentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrentry',
            name='order',
        ),
        migrations.RemoveField(
            model_name='mrentry',
            name='product',
        ),
        migrations.RemoveField(
            model_name='mrentry',
            name='quantity',
        ),
        migrations.AddField(
            model_name='mrentry',
            name='Phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mrentry',
            name='UserItem',
            field=models.ManyToManyField(blank=True, to='core.useritem'),
        ),
        migrations.AddField(
            model_name='mrentry',
            name='address',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='mrentry',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mrentry',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrentry',
            name='left',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='mrentry',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.supplier'),
        ),
    ]
