# Generated by Django 4.0.3 on 2022-08-14 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_mrentryrecord_order_mrentryrecord_mrentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrentryrecord',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.supplier'),
        ),
    ]
