# Generated by Django 4.0.3 on 2022-08-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_order_price1_remove_order_price2_sold_price1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='engine_no',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
