# Generated by Django 4.0.3 on 2022-08-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_sold_engine_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='sold',
            name='Phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
