# Generated by Django 4.0.3 on 2022-09-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_sold_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='sparename',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
