# Generated by Django 4.0.3 on 2022-09-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_sold_sparename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritem',
            name='sparename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='returnn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('returnreason', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('sold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sold')),
            ],
        ),
    ]
