# Generated by Django 4.0.3 on 2022-10-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_sold_sparename_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='totalprice',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
