# Generated by Django 4.0.3 on 2022-10-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_customer_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='quantity',
            new_name='balance',
        ),
    ]
