# Generated by Django 4.0.3 on 2022-10-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vehicleno',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
