# Generated by Django 4.0.3 on 2022-10-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_order_vehicleno'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalprice1',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
