# Generated by Django 4.0.3 on 2022-10-30 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_paybillcatogory_paybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
        migrations.AddField(
            model_name='returnn',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
