# Generated by Django 4.0.3 on 2022-11-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_product_mother'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='groupproduct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useritem',
            name='groupproduct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
