# Generated by Django 4.0.3 on 2022-11-13 06:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_sold_groupproduct_useritem_groupproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritem',
            name='enginecomplete',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete')], default='incomplete', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='dailyreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('ammount', models.DecimalField(decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
    ]
