# Generated by Django 4.0.3 on 2022-11-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_useritem_enginecomplete_dailyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='ammount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
