# Generated by Django 4.0.3 on 2022-11-19 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_alter_dailyreport_ammount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='returnn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.returnn'),
        ),
    ]
