# Generated by Django 4.0.3 on 2022-11-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_dailyreport_returnn'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnn',
            name='returnprice',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
