# Generated by Django 4.0.3 on 2022-11-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_returnn_returnprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnn',
            name='returnprice',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='returnprice',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
