# Generated by Django 4.0.3 on 2022-11-20 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_remove_returnn_returnprice_dailyreport_returnprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bill'),
        ),
    ]
