# Generated by Django 4.0.3 on 2022-11-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_rename_address_paybill_remarks_temppaybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='billexpense',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
