# Generated by Django 4.0.3 on 2022-11-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_dailyreport_billexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='reporttype',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
