# Generated by Django 4.0.3 on 2022-12-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_remove_useritem_exchange_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='groupproduct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='productype',
            field=models.CharField(choices=[('LocalContainer', ' LocalContainer'), ('publicContainer', 'publicContainer')], default='LocalContainer', max_length=100, null=True),
        ),
    ]
