# Generated by Django 4.0.3 on 2023-01-10 04:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_alter_useritem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subpartquantity',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
