# Generated by Django 4.0.3 on 2023-01-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_product_subpartquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sellprice',
        ),
    ]
