# Generated by Django 4.0.3 on 2023-01-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_remove_product_sellprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subpartquantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
