# Generated by Django 4.0.3 on 2023-01-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_alter_product_subpartquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='costprice',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sold',
            name='exchange_ammount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
