# Generated by Django 4.0.3 on 2023-01-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_sold_costprice_sold_exchange_ammount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
