# Generated by Django 4.0.3 on 2023-02-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_paybill_pettycashbalance_paybill_reloadpetteycash'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybill',
            name='typecat',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
