# Generated by Django 4.0.3 on 2023-03-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_paybill_typecat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subpartquantity1',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
