# Generated by Django 4.0.3 on 2023-03-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_product_subpartquantity1'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrentry',
            name='groupproduct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
