# Generated by Django 4.0.3 on 2023-03-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_mrentry_groupproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrentry',
            name='groupproduct',
        ),
        migrations.AddField(
            model_name='mrentryrecord',
            name='groupproduct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
