# Generated by Django 4.0.3 on 2023-03-20 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_remove_mrentry_groupproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrentryrecord',
            name='price1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
