# Generated by Django 4.0.3 on 2023-08-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_remove_mrentryrecord_mrentry_mrentry_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritem',
            name='exchange_ammount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
