# Generated by Django 4.0.3 on 2023-08-28 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_alter_useritem_exchange_ammount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
