# Generated by Django 4.0.3 on 2023-09-04 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_alter_useritem_price2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrentryrecord',
            name='order',
        ),
        migrations.AddField(
            model_name='mrentryrecord',
            name='mrentry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mrentry'),
        ),
    ]
