# Generated by Django 4.0.3 on 2023-09-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_order_invoicenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnn',
            name='status',
            field=models.CharField(choices=[('CASH RETUEN', 'CASH RETUEN'), (' WITH OUT CASH RETUEN', 'WITH OUT CASH RETUEN')], default='CASH RETUEN', max_length=50, null=True),
        ),
    ]
