# Generated by Django 4.0.3 on 2023-09-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_returnn_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnn',
            name='retunprice',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
