# Generated by Django 4.0.3 on 2023-09-25 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_returnn_retunprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnn',
            old_name='retunprice',
            new_name='returnprice',
        ),
    ]
