# Generated by Django 4.0.3 on 2023-09-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_rename_retunprice_returnn_returnprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnn',
            name='cashreturnprice',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='returnn',
            name='duereturnprice',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
