# Generated by Django 4.0.3 on 2024-02-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_remove_corportepay_groupproduct_corportepay_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='remarks',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
