# Generated by Django 4.0.3 on 2024-02-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_alter_dailyreport_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybill',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
