# Generated by Django 4.0.3 on 2024-02-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_alter_paybill_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='remarks',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
