# Generated by Django 4.0.3 on 2024-02-11 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_alter_dailyreport_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corportepay',
            name='remarks',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Customerbalacesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueblaceadd', models.PositiveIntegerField(default=0, null=True)),
                ('billreceive', models.PositiveIntegerField(default=0, null=True)),
                ('balance', models.PositiveIntegerField(default=0, null=True)),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='core.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.order')),
            ],
        ),
    ]
