# Generated by Django 4.0.3 on 2024-03-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_alter_corportepay_remarks_customerbalacesheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='left',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subpartquantity1',
        ),
    ]
