# Generated by Django 4.0.3 on 2024-03-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_alter_customerbalacesheet_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='returnquantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='returnn',
            name='status',
            field=models.CharField(choices=[('CASH RETUEN', 'CASH RETUEN'), (' DUE RETURN', 'DUE RUTURN'), (' BOTH', 'BOTH')], default='CASH RETUEN', max_length=50, null=True),
        ),
    ]
