# Generated by Django 4.0.3 on 2024-03-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_sold_returnquantity_alter_returnn_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='billinvoiceid',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='name',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='returnn',
            name='status',
            field=models.CharField(choices=[('CASH RETURN', 'CASH RETURN'), ('DUE RUTURN', 'DUE RUTURN'), ('BOTH', 'BOTH')], default='CASH RETURN', max_length=50, null=True),
        ),
    ]
