# Generated by Django 4.0.3 on 2024-03-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_bill_billinvoiceid_alter_bill_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='smssend',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='billinvoiceid',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='name',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
