# Generated by Django 4.0.3 on 2024-03-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_order_smssend_alter_bill_billinvoiceid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='smssend',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
